language: cpp
dist: trusty

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi

install:
  - cmake -version

script: ./go.sh setup && ./go.sh build-host && ./go.sh test-host && ./go.sh build-target
